SPARQLingUnicornQGISPlugin: CheckableComboBox Class Reference
CheckableComboBox Class Reference
Classes
class Delegate
Public Member Functions
def __init__ (self, *args, **kwargs)
def resizeEvent (self, event)
def eventFilter (self, object, event)
def showPopup (self)
def hidePopup (self)
def timerEvent (self, event)
def updateText (self)
def addItem (self, text, data=None)
def addItems (self, texts, datalist=None)
def currentData (self)
Public Attributes
closeOnLineEditClick
Constructor & Destructor Documentation
__init__()
def __init__ (self, * args, ** kwargs)
     def __init__(self, *args, **kwargs):
         super().__init__(*args, **kwargs)
         # Make the combo editable to set a custom text, but readonly
         self.setEditable(True)
         self.lineEdit().setReadOnly(True)
         # Make the lineedit the same color as QPushButton
         # palette = qApp.palette()
         # palette.setBrush(QPalette.Base, palette.button())
         # self.lineEdit().setPalette(palette)
         # Use custom delegate
         self.setItemDelegate(CheckableComboBox.Delegate())
         # Update the text when an item is toggled
         self.model().dataChanged.connect(self.updateText)
         # Hide and show popup when clicking the line edit
         self.lineEdit().installEventFilter(self)
         self.closeOnLineEditClick = False
         # Prevent popup from closing when clicking on an item
         self.view().viewport().installEventFilter(self)
References CheckableComboBox.updateText().
Member Function Documentation
addItem()
def addItem (self, text, data = None)
     def addItem(self, text, data=None):
         item = QStandardItem()
         item.setText(text)
         if data is None:
             item.setData(text)
         else:
             item.setData(data)
         item.setFlags(Qt.ItemIsEnabled | Qt.ItemIsUserCheckable)
         item.setData(Qt.Unchecked, Qt.CheckStateRole)
         self.model().appendRow(item)
Referenced by CheckableComboBox.addItems().
addItems()
def addItems (self, texts, datalist = None)
     def addItems(self, texts, datalist=None):
         for i, text in enumerate(texts):
             try:
                 data = datalist[i]
             except (TypeError, IndexError):
                 data = None
             self.addItem(text, data)
References CheckableComboBox.addItem().
currentData()
def currentData (self)
     def currentData(self):
         # Return the list of selected items data
         res = []
         for i in range(self.model().rowCount()):
             if self.model().item(i).checkState() == Qt.Checked:
                 res.append(self.model().item(i).data())
         return res
eventFilter()
def eventFilter (self, object, event)
     def eventFilter(self, object, event):
         if object == self.lineEdit():
             if event.type() == QEvent.MouseButtonRelease:
                 if self.closeOnLineEditClick:
                     self.hidePopup()
                 else:
                     self.showPopup()
                 return True
             return False
         if object == self.view().viewport():
             if event.type() == QEvent.MouseButtonRelease:
                 index = self.view().indexAt(event.pos())
                 item = self.model().item(index.row())
                 if item.checkState() == Qt.Checked:
                     item.setCheckState(Qt.Unchecked)
                 else:
                     item.setCheckState(Qt.Checked)
                 return True
         return False
References CheckableComboBox.closeOnLineEditClick, CheckableComboBox.hidePopup(), and CheckableComboBox.showPopup().
hidePopup()
def hidePopup (self)
     def hidePopup(self):
         super().hidePopup()
         # Used to prevent immediate reopening when clicking on the lineEdit
         self.startTimer(100)
         # Refresh the display text when closing
         self.updateText()
References CheckableComboBox.updateText().
Referenced by CheckableComboBox.eventFilter().
resizeEvent()
def resizeEvent (self, event)
     def resizeEvent(self, event):
         # Recompute text to elide as needed
         self.updateText()
         super().resizeEvent(event)
References CheckableComboBox.updateText().
showPopup()
def showPopup (self)
     def showPopup(self):
         super().showPopup()
         # When the popup is displayed, a click on the lineedit should close it
         self.closeOnLineEditClick = True
References CheckableComboBox.closeOnLineEditClick.
Referenced by CheckableComboBox.eventFilter().
timerEvent()
def timerEvent (self, event)
     def timerEvent(self, event):
         # After timeout, kill timer, and reenable click on line edit
         self.killTimer(event.timerId())
         self.closeOnLineEditClick = False
References CheckableComboBox.closeOnLineEditClick.
updateText()
def updateText (self)
     def updateText(self):
         texts = []
         for i in range(self.model().rowCount()):
             if self.model().item(i).checkState() == Qt.Checked:
                 texts.append(self.model().item(i).text())
         text = ", ".join(texts)
         # Compute elided text (with "...")
         metrics = QFontMetrics(self.lineEdit().font())
         elidedText = metrics.elidedText(text, Qt.ElideRight, self.lineEdit().width())
         self.lineEdit().setText(elidedText)
Referenced by CheckableComboBox.__init__(), CheckableComboBox.hidePopup(), and CheckableComboBox.resizeEvent().
Member Data Documentation
closeOnLineEditClick
closeOnLineEditClick
Referenced by CheckableComboBox.eventFilter(), CheckableComboBox.showPopup(), and CheckableComboBox.timerEvent().